services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi 
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  postgres.database:
      image: postgres:latest
      volumes:
        - G:\PostGreSQL\data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      volumes:
        - G:\PostGreSQL\pg-admin\data:/var/lib/pgadmin
  